"""T2.2 — `tta run-all` orchestration and top-level index page."""

from __future__ import annotations

from pathlib import Path
from typing import Any

import click
import jinja2

from text_theme_analyzer.config import Config, OutputFormat, _apply_corpus_overrides
from text_theme_analyzer.output.cli_summary import render_cli
from text_theme_analyzer.output.html_dashboard import write_html
from text_theme_analyzer.output.json_report import write_json
from text_theme_analyzer.output.markdown_report import write_markdown
from text_theme_analyzer.pipeline.model import Analysis
from text_theme_analyzer.pipeline.orchestrator import run as run_pipeline
from text_theme_analyzer.utils.progress import log

INDEX_TEMPLATE = """<!DOCTYPE html>
<html lang=\"en\">
<head>
  <meta charset=\"UTF-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">
  <title>Text Theme Analyzer — Corpora</title>
  <style>
    :root { color-scheme: light dark; }
    body { font-family: system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; line-height: 1.5; }
    h1 { font-size: 1.6rem; margin-bottom: 0.5rem; }
    p { color: #666; }
    ul { list-style: none; padding: 0; }
    li { margin: 0.8rem 0; }
    a { display: block; padding: 1rem; border: 1px solid #ccc; border-radius: 8px; text-decoration: none; color: inherit; }
    a:hover { background: #f5f5f5; }
    .name { font-weight: 600; font-size: 1.1rem; }
    .meta { color: #777; font-size: 0.9rem; margin-top: 0.25rem; }
  </style>
</head>
<body>
  <h1>Thinking radars</h1>
  <p>Per-corpus dashboards generated by <code>tta run-all</code>.</p>
  <ul>
  {% for c in corpora %}
    <li>
      <a href=\"{{ c.rel_html }}\">
        <div class=\"name\">{{ c.name }}</div>
        <div class=\"meta\">{{ c.notes }} notes · {{ c.clusters }} clusters · {{ c.output_dir }}</div>
      </a>
    </li>
  {% endfor %}
  </ul>
</body>
</html>
"""


def _render_index(
    corpora: list[dict[str, Any]],
    *,
    env: jinja2.Environment | None = None,
) -> str:
    """Render the top-level index HTML linking to each corpus dashboard."""
    if env is None:
        env = jinja2.Environment(autoescape=True)
    template = env.from_string(INDEX_TEMPLATE)
    return template.render(corpora=corpora)


def _write_index(output_dir: Path, corpora: list[dict[str, Any]]) -> Path:
    """Write corpora/index.html under the global output dir."""
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "corpora" / "index.html"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_render_index(corpora), encoding="utf-8")
    return path


def _effective_outputs(config: Config) -> list[OutputFormat]:
    """Default run-all outputs to markdown+json+html if the user didn't specify."""
    if config.outputs == [OutputFormat.CLI]:
        return [OutputFormat.MARKDOWN, OutputFormat.JSON, OutputFormat.HTML]
    return config.outputs


def _write_corpus_outputs(analysis: Analysis, config: Config) -> dict[str, Path | None]:
    """Write the configured output formats for one corpus. Returns format -> path."""
    written: dict[str, Path | None] = {}
    for fmt in _effective_outputs(config):
        if fmt == OutputFormat.MARKDOWN:
            written["markdown"] = write_markdown(analysis, config.output_dir, top_n_themes=config.top_n_themes)
        elif fmt == OutputFormat.JSON:
            written["json"] = write_json(analysis, config.output_dir)
        elif fmt == OutputFormat.HTML:
            written["html"] = write_html(analysis, config.output_dir)
        elif fmt == OutputFormat.CLI:
            render_cli(analysis, top_n_themes=config.top_n_themes)
            written["cli"] = None
    return written


def run_all(
    base_config: Config,
    *,
    write_history: bool = True,
) -> tuple[list[tuple[str, Analysis, dict[str, Path | None]]], Path]:
    """Run the analyzer on every configured corpus and emit a top-level index.

    Returns a list of (corpus_name, analysis, written_paths) plus the path to
    the generated index HTML.
    """
    if not base_config.corpora:
        raise click.UsageError("No corpora configured. Add a `corpora:` block to text-theme-analyzer.yml.")

    results: list[tuple[str, Analysis, dict[str, Path | None]]] = []
    index_rows: list[dict[str, Any]] = []

    for name, corpus_cfg in base_config.corpora.items():
        cfg = _apply_corpus_overrides(base_config, name, corpus_cfg)
        log(f"[run-all] {name}: {cfg.input_path} -> {cfg.output_dir}", quiet=cfg.quiet)
        analysis = run_pipeline(cfg)
        written = _write_corpus_outputs(analysis, cfg)

        if write_history:
            try:
                from text_theme_analyzer.output.history import (
                    snapshot_from_analysis,
                    write_snapshot,
                )
                snap = snapshot_from_analysis(analysis)
                snap_path = write_snapshot(snap, cfg.output_dir)
                log(f"[run-all] {name} snapshot {snap_path.name}", quiet=cfg.quiet)
            except Exception as e:
                log(f"[run-all] {name} could not write snapshot: {e}", quiet=cfg.quiet)

        results.append((name, analysis, written))
        n_clusters = len(analysis.clusters.cluster_keywords) if analysis.clusters else 0
        rel_html = ""
        if html_path := written.get("html"):
            try:
                rel_html = str(html_path.relative_to(base_config.output_dir))
            except ValueError:
                rel_html = str(html_path)
        index_rows.append({
            "name": name,
            "output_dir": str(cfg.output_dir),
            "notes": len(analysis.notes),
            "clusters": n_clusters,
            "rel_html": rel_html,
        })

    index_path = _write_index(base_config.output_dir, index_rows)
    return results, index_path
